version: '3.9'

x-base_service: &base_service
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - &v1 "${DATA_PATH:-./data}:/data"
      - &v2 "${OUTPUT_PATH:-./output}:/output"
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: stable-diffusion-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:72
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  invoke: &invoke
    <<: *base_service
    profiles: ["invoke"]
    build: ./services/invoke/
    image: sd-invoke:30
    environment:
      - PRELOAD=true
      - CLI_ARGS=--xformers

  # invoke-cpu:
  #   <<: *invoke
  #   profiles: ["invoke-cpu"]
  #   environment:
  #     - PRELOAD=true
  #     - CLI_ARGS=--always_use_cpu

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:1958
    environment:
      - CLI_ARGS=


  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu


# Testing Area Below
  myauto:
    <<: *automatic
    profiles: ["myauto"]
    environment:
      - CLI_ARGS=--api --xformers --no-half-vae --opt-sub-quad-attention --upcast-sampling --allow-code --enable-insecure-extension-access

  mycomfy:
    <<: *comfy
    profiles: ["mycomfy"]
    volumes:
      - *v1
      - *v2
      - ./data/config/comfy/custom_nodes:/stable-diffusion/custom_nodes
      - ./data/config/comfy/models:/stable-diffusion/models
      - ./data/config/comfy/my_workflows:/stable-diffusion/my_workflows
    environment:
      - CLI_ARGS=--multi-user
      
  mylorascripts:
    <<: *base_service
    profiles: ["mylorascripts"]
    build: ./services/lora-scripts
    image: lora-scripts:183
    environment:
      - CLI_ARGS=

  myfooocus: &myfooocus
    <<: *base_service
    profiles: ["myfooocus"]
    build: ./services/Fooocus
    image: fooocus:21
    environment:
      - CLI_ARGS=

  myfooocus-animate:
    <<: *myfooocus
    profiles: ["myfooocus-animate"]
    environment:
      - CLI_ARGS=--preset anime

  myfooocus-realistic:
    <<: *myfooocus
    profiles: ["myfooocus-realistic"]
    environment:
      - CLI_ARGS=--preset realistic

  myforge:
    <<: *base_service
    profiles: ["myforge"]
    build: ./services/forge
    image: sd-forge:17
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api